### ISSUE TITLE
uvloop doesn't support Windows

### ISSUE THREAD

**Issue by dawnwages** [Azure-Samples/chatgpt-quickstart#205]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> `pip install -r requirements-dev.txt`

### Any log messages given by the failure
>   RuntimeError: uvloop does not support Windows at the moment
      [end of output]

### Expected/desired behavior
> requirements install

### OS and Version?
> Windows 11 Enterprise

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
This should now be fixed, tests are passing on Windows.
