### ISSUE TITLE
[Nice to have] Use existing OpenAI deployment

### ISSUE THREAD

**Issue by fabiobo2005** [Azure-Samples/chatgpt-quickstart#9]
Due to Azure restriction and quota limitation would be nice to have an option to select an existing OpenAI service in the same subscription or tenant.

I tried to configure the .env.sample file with my own OpenAI endpoint, but azd up failed to create and deploy and I dont know how to redeploy it.

**Comment by pamelafox** [comment]
I'll look into improving that workflow, thanks for filing!

**Comment by pamelafox** [comment]
@fabiobo2005 Can you try now? I've updated the README with instructions:
https://github.com/Azure-Samples/chatgpt-quickstart#deployment-with-existing-resources
